#!/bin/bash
# FIXME: Could this be a more generic install script?


INIFILE=server.ini   
JDBCDRIVER="/usr/share/java/postgresql-jdbc4.jar"
CLASSPATH=polaric-aprsd.jar:polaric-db.jar:/usr/share/java/commons-dbcp.jar:/usr/share/java/commons-pool.jar:/usr/share/java/commons-collections.jar:$JDBCDRIVER

###################################################
# We dont need to change anything below this line
###################################################

java -cp $CLASSPATH no.polaric.aprsdb.DbInstaller $INIFILE $*
echo "Done."
     
