#!/bin/bash
set -e


case "$1" in
    remove)
       polaric-pluginctl /etc/polaric-aprsd/confid.d/database.ini deactivate
       echo "Please restart aprsd when ready" 
    ;;

    purge)
        # Nothing to do here
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
