#!/bin/bash
set -e
INIFILE=/etc/polaric-aprsd/server.ini

# Source debconf library.
. /usr/share/debconf/confmodule


case "$1" in

    configure|reconfigure)
      if [ -e "/etc/polaric-aprsd/plugins/postgis.jar" ]; then
         rm /etc/polaric-aprsd/plugins/postgis.jar
      fi   
      echo 
      echo "Database plugin is now installed."
      echo "To install, configure and connect a database, and to activate the"
      echo "plugin, you may need to run the following commands:"
      echo
      echo "   polaric-dbsetup (if database is not installed already)"
      echo "   polaric-restart"
      echo
    
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
