#!/bin/bash
set -e
INIFILE=/etc/polaric-aprsd/server.ini

# Source debconf library.
. /usr/share/debconf/confmodule


case "$1" in

    configure|reconfigure)
      if [ -e "/etc/polaric-aprsd/plugins/postgis.jar" ]; then
         rm /etc/polaric-aprsd/plugins/postgis.jar
      fi   
      ln -s /usr/share/java/postgis-jdbc.jar /etc/polaric-aprsd/plugins/postgis.jar
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
