#!/bin/bash

   DBNAME=polaric
 USERNAME=polaric



# We have to be the postgres user
if [ $(whoami) != "postgres" ]; then
    echo "ERROR: This script must be run as the 'postgres' user"
    exit 1
fi




VERSION=$(psql -t -c 'select version from "MetaData"' polaric | xargs)

echo "Version is $VERSION"
if ((VERSION < 2)); then
    echo "Upgrading schema to version 2"
    
    psql -t -c "BEGIN;  \
        CREATE TABLE \"ObjectAccess\" ( \
        id  integer REFERENCES \"JsObject\" (id) ON DELETE CASCADE, \
        readonly boolean DEFAULT 'false', \
        userid  varchar(20) ); \
        \
        INSERT INTO \"ObjectAccess\" ( id, userid, readonly) \
        SELECT id, userid, 'false' FROM \"JsObject\"; \
        \
        ALTER TABLE \"JsObject\" DROP COLUMN \"userid\"; \
        ALTER TABLE \"ObjectAccess\" owner TO polaric; \
        UPDATE \"MetaData\" SET version=2; \
        COMMIT " polaric
fi

if ((VERSION < 3)); then
    echo "Upgrading schema to version 3"
    
    psql -t -c "BEGIN;  \
        DROP TABLE \"FileObject\"; \
        UPDATE \"MetaData\" SET version=3; \
        COMMIT " polaric
fi

if ((VERSION < 4)); then
    echo "Upgrading schema to version 4"
    
    psql -t -c "BEGIN;  \
        CREATE TABLE \"TrTags\" ( \
        userid  varchar(20) NOT NULL, \
        tag varchar(20) NOT NULL ); \
        ALTER TABLE \"TrTags\" owner to polaric; \
        CREATE INDEX aprspacket_src_time_idx on \"AprsPacket\" (src, time); \
        COMMIT " polaric
fi

NSCLASS=$(psql -t -c 'select count(*) from "SignClass"' polaric | xargs)
if ((NSCLASS == 0)); then
    echo "Adding classes/icons in \"SignClass\""
    echo "NOTE: You may change/add classes in the PostgreSQL database"
    psql -t -c "BEGIN; \
        INSERT INTO \"SignClass\" (id,name,icon) values (0, 'Default', 'signs/point.png'); \
        INSERT INTO \"SignClass\" (id,name,icon) values (1, 'Info', 'signs/info.png'); \
        INSERT INTO \"SignClass\" (id,name,icon) values (8, 'Radio installation', 'signs/signal.png'); \
        COMMIT " polaric
fi

