#!/bin/bash

   INIFILE=/etc/polaric-aprsd/config.d/database.ini   
JDBCDRIVER="/usr/share/java/postgresql-jdbc4.jar"
 CLASSPATH=/usr/share/java/polaric-aprsd.jar:/usr/share/java/polaric-db.jar:/usr/share/java/commons-dbcp.jar:/usr/share/java/commons-pool.jar:/usr/share/java/commons-collections.jar:$JDBCDRIVER
 

   
# We have to be the superuser
if [ $(whoami) != "root" ]; then
    echo "ERROR: This script must be run as the superuser (root)"
    exit 1
fi

echo 
echo "This script will install and configure a database on this host and "
echo "connect the polaric-aprsd plugin to this database. It may need an" 
echo "active internet connection to fetch some software packages."
echo
echo "If database is already installed, you don't need to run this script." 
echo "It will erase all data and start from scratch.."
echo
read -p "Do you want to continue? [Y/n]" -n 1 -r

if [[ $REPLY =~ ^[^Yy]$ ]]
then
    exit 0
fi


# Install packages
echo 
echo "Installing software packages..."
apt-get -q -y install postgresql postgis
[ $? -eq 0 ] || exit 1  

#
# Generate a 16 character random password
#
PASSWD=$(< /dev/urandom tr -dc [:alnum:][:graph:] | head -c${1:-16})


#
# Setup database with PostGIS, etc.. 
# Run script as postgres user passing the database password as argument
#
echo
echo "Initializing database.."
su -c "polaric-dbsetup-first '$PASSWD'" - postgres
[ $? -eq 0 ] || exit 1 

 
# 
# Set password in ini file
# Activate the plugin
#
sed -i -E "s/db\.passwd = .*/db\.passwd = $PASSWD/g" $INIFILE
sed -i -E "s/db\.plugin\.on = false/db\.plugin\.on = true/g" $INIFILE
 
#
# Run Java db installer program
#
echo
echo "Creating and initializing application specific database tables"
java -cp $CLASSPATH no.polaric.aprsdb.DbInstaller $INIFILE $*
echo
echo "Done."
     
